parameters: {}
environment:
  REDIRECT_URL: https://google.com
packages:
    - name: main
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: redirect
          binary: false
          main: ""
          runtime: nodejs:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
